### ISSUE TITLE
How to get the static-openstreetmap image?

### ISSUE THREAD

**Issue by kirantpatil** [warpech/static-openstreetmap#3]
Hi,

I would like to get the image of it in jpeg/jpg format.

How to do it ?

Thanks.

**Comment by warpech** [comment]
The image is rendered by the http://staticmap.openstreetmap.de/ web service. The rendering is only available in PNG. If you would like to have JPG, you need to fork their source (it is open source) and run your own server. Or, use their server and convert the PNG to JPG.
